Allowed use of old versions form puppetlabs repo
* Prevented circular dependencies between mcollective and
mcollective-common when not using last version from puppetlabs
repo

Error message
==========
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o
DPkg::Options::=--force-confold --force-yes install
mcollective=2.7.0-1puppetlabs1' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mcollective : Depends: mcollective-common (= 2.7.0-1puppetlabs1) but
 2.8.0-1puppetlabs1 is to be installed
E: Unable to correct problems, you have held broken packages.
Wrapped exception:
Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold
 --force-yes install mcollective=2.7.0-1puppetlabs1' returned 100:
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
===========